const codeImage = {
  "0": "../../asset/WeatherIcon - 2-22.svg",
  "1": "Principalement clair",
  "2": "partiellement nuageux",
  "3": "nuageux",
  "45": "Brouillard",
  "48": "Dépôt de brouillard givré",
  "51": "Bruine : Intensité légère",
  "53": "Bruine : modérée",
  "55": "Bruine : dense",
  "56":"Brouillard givrant : Intensité légère",
  "57":"Brouillard givrant : dense",
  "61":"Pluie : intensité légère",
  "63":"Pluie : intensité modérée",
  "65":"Pluie : intensité forte",
  "66":"Pluie verglaçante : Intensité légère",
  "67":"Pluie verglaçante : Intensité forte",
  "71":"Chutes de neige : Intensité légère",
  "73":"Chutes de neige : Intensité modérée",
  "75":"Chutes de neige : Intensité forte",
  "77":"Grains de neige",
  "80":"Averses de pluie : Légères",
  "81":"Averses de pluie : modérées",
  "82":"Averses de pluie : violentes",
  "85":"averses de neige légères",
  "86":"averses de neige fortes",
  "95 *":"Orage : Léger ou modéré",
  "96 *":"Orage avec grêle légère",
  "99 *":"Orage avec grêle forte"
};

export default codeImage;
